name: Sync yuque To Github

on:
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - start

jobs:
  yuque:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Sync yuque
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          npm run yuque:clean
          npm run yuque:sync

      - name: Git Commit
        run: |
          git config --local user.name "soonwang"
          git config --local user.email "wangsong3635@outlook.com"
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh yuque json" -a

      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          npm run hexo:clean
          npm run hexo:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch
